django_project/urls.py
from django.contrib import admin
from django.urls import path, include

urlpatterns = [
    path('admin/', admin.site.urls),
    path('', include('employees.urls')),
    path('i18n/', include('django.conf.urls.i18n')),
]

employees/urls.py
from django.urls import path, include
from django.conf import settings
from django.conf.urls.static import static
from django.contrib.auth import views as auth_views

from .views import CustomPasswordResetConfirmView, delete_external_permission, delete_internal_permission, \
    create_invitation, register

from . import views

from django.urls import re_path
from django.views.static import serve

urlpatterns = [
                  path('', views.index, name='index'),
                  path('<int:id>', views.view_employee, name='view_employee'),
                  path('add/', views.add_employee, name='add'),
                  path('edit/<int:pk>/', views.edit_employee, name='edit_employee'),
                  path('delete/<int:pk>/', views.delete, name='delete'),
                  path('active/', views.valid_employees, name='active_employees'),
                  path('inactive/', views.inactive_employees, name='inactive_employees'),
                  path('reactivate/<int:id>/', views.reactivate_employee, name='reactivate_employee'),
                  path('add_internal_permission/<int:employee_id>/', views.add_internal_permission,
                       name='add_internal_permission'),
                  path('add_external_permission/<int:employee_id>/', views.add_external_permission,
                       name='add_external_permission'),
                  path('edit_internal_permission/<int:permission_id>/', views.edit_internal_permission,
                       name='edit_internal_permission'),
                  path('edit_external_permission/<int:permission_id>/', views.edit_external_permission,
                       name='edit_external_permission'),
                  path('employee/<int:pk>/delete_permanently/', views.delete_employee_permanently,
                       name='delete_employee_permanently'),
                  path('delete_internal_permission/<int:permission_id>/', delete_internal_permission,
                       name='delete_internal_permission'),
                  path('delete_external_permission/<int:permission_id>/', delete_external_permission,
                       name='delete_external_permission'),
                  path('logout/', auth_views.LogoutView.as_view(next_page='login'), name='logout'),
                  path('accounts/', include('django.contrib.auth.urls')),
                  path('password_reset/',
                       auth_views.PasswordResetView.as_view(template_name='registration/password_reset_form.html'),
                       name='password_reset'),
                  path('password_reset/done/',
                       auth_views.PasswordResetDoneView.as_view(template_name='registration/password_reset_done.html'),
                       name='password_reset_done'),
                  path('reset/<uidb64>/<token>/', CustomPasswordResetConfirmView.as_view(),
                       name='password_reset_confirm'),
                  path('create_invitation/', create_invitation, name='create_invitation'),
                  path('register/', register, name='register'),
                  path('expired_token/', register, name='expired_token'),
                  path('employee/<int:id>/profile/', views.employee_profile, name='employee_profile'),
                  path('departments/', views.departments, name='departments'),
                  path('departments/<int:department_id>/employees/', views.department_employees, name='department_employees'),
                  path('settings/', views.user_settings, name='user_settings'),

              ]

if settings.DEBUG:
    urlpatterns += static(settings.MEDIA_URL, document_root=settings.MEDIA_ROOT)
    urlpatterns += static(settings.STATIC_URL, document_root=settings.STATIC_ROOT)

employees/models.py
from django.utils.translation import gettext_lazy as _
from django.db import models
from django.utils import timezone

from PIL import Image

from datetime import timedelta, date

import uuid


class Employee(models.Model):
    VERIFICATION_ACTIVE = "A"
    VERIFICATION_INACTIVE = "I"
    VERIFICATION_ACTIVE_NAME = "Active"
    VERIFICATION_INACTIVE_NAME = "Inactive"

    VERIFICATION_CHOICES = [
        (VERIFICATION_ACTIVE, VERIFICATION_ACTIVE_NAME),
        (VERIFICATION_INACTIVE, VERIFICATION_INACTIVE_NAME),
    ]

    first_name = models.CharField(max_length=255, verbose_name=_('First name'))
    last_name = models.CharField(max_length=255, verbose_name=_('Last name'))
    photo = models.ImageField(upload_to='employee_photos/', default='default_photo.jpg', blank=True, null=True,
                              verbose_name=_('Photo'))
    hire_date = models.DateField(default=None, null=True, verbose_name=_('Hire date'))
    department = models.ForeignKey('Department', on_delete=models.CASCADE, verbose_name=_('Department'))
    position = models.ForeignKey('Position', on_delete=models.CASCADE, verbose_name=_('Position'))
    verification = models.CharField(max_length=1, choices=VERIFICATION_CHOICES, default=VERIFICATION_ACTIVE,
                                    verbose_name=_('Verification'))
    attachment = models.FileField(upload_to='employees/', null=True, blank=True, verbose_name=_('Attachment'))

    def __str__(self):
        return f'{self.first_name} {self.last_name}'

    class Meta:
        ordering = ['first_name']
        verbose_name_plural = _('Employees')
        verbose_name = _('Employee')

    def save(self, *args, **kwargs):
        super().save(*args, **kwargs)

        if self.photo:
            img = Image.open(self.photo.path)

            img.thumbnail((300, 300), Image.Resampling.LANCZOS)

            img_width, img_height = img.size
            if img_width > 300 or img_height > 300:
                left = (img_width - 300) / 2
                top = (img_height - 300) / 2
                right = (img_width + 300) / 2
                bottom = (img_height + 300) / 2
                img = img.crop((left, top, right, bottom))

            img.save(self.photo.path)


class Employee_information(models.Model):
    employee = models.OneToOneField(Employee, on_delete=models.CASCADE, primary_key=True, verbose_name=_('Employee'))
    date_of_birth = models.DateField(null=True, blank=True, verbose_name=_('Date of birth'))
    email = models.EmailField(unique=True, null=True, blank=True, verbose_name=_('Email'))
    phone_number = models.CharField(max_length=255, unique=True, null=True, blank=True, default=None,
                                    verbose_name=_('Phone number'))
    address = models.CharField(max_length=1500, null=True, blank=True, verbose_name=_('Address'))

    def __str__(self):
        return f'{self.employee.first_name} {self.employee.last_name}'

    class Meta:
        ordering = ['employee__first_name']
        verbose_name_plural = _('Employee information')

    def is_birthday_today(self):
        return self.date_of_birth.month == date.today().month and \
            self.date_of_birth.day == date.today().day


class Department(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_('Name'))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = _('Departments')
        verbose_name = _('Department')


class Position(models.Model):
    name = models.CharField(max_length=50, unique=True, verbose_name=_('Name'))

    def __str__(self):
        return self.name

    class Meta:
        ordering = ['name']
        verbose_name_plural = _('Positions')
        verbose_name = _('Position')


class Internal_permission(models.Model):
    TAG_SECRET = _('S')
    TAG_CONFIDENTIAL = _('C')
    TAG_RESTRICTED = _('R')
    TAG_REJECTED = _('X')
    TAG_SECRET_NAME = _('Secret')
    TAG_CONFIDENTIAL_NAME = _('Confidential')
    TAG_RESTRICTED_NAME = _('Restricted')
    TAG_REJECTED_NAME = _('Rejected')

    TAG_CHOICES = [
        (TAG_SECRET, TAG_SECRET_NAME),
        (TAG_CONFIDENTIAL, TAG_CONFIDENTIAL_NAME),
        (TAG_RESTRICTED, TAG_RESTRICTED_NAME),
        (TAG_REJECTED, TAG_REJECTED_NAME),
    ]

    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name=_('Employee'))
    permit_number = models.CharField(max_length=10, unique=True, null=True, blank=True, verbose_name=_('Permit number'))
    permit_issue_date = models.DateField(verbose_name=_('Permit issue date'))
    permit_expiry_date = models.DateField(verbose_name=_('Permit expiry date'))
    description = models.TextField(max_length=255, null=True, blank=True, verbose_name=_('Description'))
    tag = models.CharField(max_length=2, choices=TAG_CHOICES, default=TAG_REJECTED, verbose_name=_('Tag'))
    attachment = models.FileField(upload_to='internal_permissions/', null=True, blank=True,
                                  verbose_name=_('Attachment'))

    @property
    def is_expiring_or_expired(self):
        today = timezone.now().date()
        six_months_ahead = today + timedelta(days=30 * 6)
        if self.permit_expiry_date < today:
            return 'expired'
        elif self.permit_expiry_date <= six_months_ahead:
            return 'expiring'
        else:
            return 'active'

    def __str__(self):
        return f'{self.employee.first_name} {self.employee.last_name} {self.permit_number}'

    class Meta:
        ordering = ['employee__first_name']
        verbose_name_plural = _('Internal permissions')
        verbose_name = _('Internal permission')


class External_permission(models.Model):
    employee = models.ForeignKey(Employee, on_delete=models.CASCADE, verbose_name=_('Employee'))
    permit_number = models.CharField(max_length=10, unique=True, null=True, blank=True, verbose_name=_('Permit number'))
    permit_issue_date = models.DateField(verbose_name=_('Permit issue date'))
    permit_expiry_date = models.DateField(verbose_name=_('Permit expiry date'))
    attachment = models.FileField(upload_to='external_permissions/', null=True, blank=True,
                                  verbose_name=_('Attachment'))

    @property
    def is_expiring_or_expired(self):
        today = timezone.now().date()
        six_months_ahead = today + timedelta(days=30 * 6)
        if self.permit_expiry_date < today:
            return 'expired'
        elif self.permit_expiry_date <= six_months_ahead:
            return 'expiring'
        else:
            return 'active'

    def __str__(self):
        return f'{self.employee.first_name} {self.employee.last_name} {self.permit_number}'

    class Meta:
        ordering = ['employee__first_name']
        verbose_name_plural = _('External permissions')
        verbose_name = _('External permission')


class DeactivationLog(models.Model):
    employee = models.OneToOneField(Employee, on_delete=models.CASCADE, primary_key=True, verbose_name=_('Employee'))
    deactivation_date = models.DateField(null=True, blank=True, verbose_name=_('Deactivation date'))
    comments = models.TextField(null=True, blank=True, verbose_name=_('Comments'))

    def __str__(self):
        return f'{self.employee.first_name} {self.employee.last_name}'

    class Meta:
        verbose_name_plural = _('Deactivation logs')
        verbose_name = _('Deactivation log')


class Invitation(models.Model):
    email = models.EmailField(unique=False, verbose_name=_('Email'))
    token = models.UUIDField(default=uuid.uuid4, editable=False, verbose_name=_('Token'))
    is_used = models.BooleanField(default=False, verbose_name=_('Is used'))
    is_expired = models.BooleanField(default=False, verbose_name=_('Is expired'))
    created_at = models.DateTimeField(auto_now_add=True, verbose_name=_('Created at'))

    def __str__(self):
        return self.email

    class Meta:
        verbose_name_plural = _('Invitations')
        verbose_name = _('Invitation')

employees/templates/employees/add.html
{% extends 'employees/base.html' %}
{% load i18n %}

{% block body %}
<h3 class="text-center m-4"></h3>
{% if success %}
<div class="alert alert-success" role="alert">
  {% trans "New employee added successfully!" %}
  <a href="{% url 'active_employees' %}" class="alert-link">{% trans "Employee list" %}</a>
  {% trans "or" %}
  <a href="{% url 'index' %}" class="alert-link">{% trans "Home" %}</a>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card bg-light mb-3">
      <div class="card-header">
        <i class="fa-solid fa-address-card fa-lg"></i> {% trans "New Employee" %}
      </div>
      <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data" id="addEmployeeForm">
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">{% trans "Add" %}</button>
          <a href="{% url 'active_employees' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}

<script src="https://ajax.googleapis.com/ajax/libs/jquery/3.5.1/jquery.min.js"></script>
<script src="https://cdnjs.cloudflare.com/ajax/libs/select2/4.0.13/js/select2.min.js"></script>
<script>
$(document).ready(function() {
    var departmentsData = {{ departments_json | safe }};

    $('#id_department').select2({
        theme: 'bootstrap4',
        data: departmentsData,
        tags: true,
        createTag: function (params) {
            var term = $.trim(params.term);
            if (term === '') {
                return null;
            }

            // Basic AJAX for Department Creation
            $.ajax({
                url: "{% url 'add_employee' %}", // Adjust URL if needed
                type: 'POST',
                data: {
                    'department_name': term,
                    'is_ajax': true // To let your view know it's an AJAX request
                 },
                 dataType: 'json',
                 success: function (response) {
                     if (response.success) {
                         // Create new Select2 option
                         var newOption = new Option(term, response.department_id, false, true);
                         $('#id_department').append(newOption).trigger('change');
                     } else {
                         // Handle potential errors here
                         alert("Error creating department!");
                     }
                 }
            });

            return null;
        }
    });
});
</script>

{% endblock %}

employees/templates/employees/add_external_permission.html
{% extends 'employees/base.html' %}

{% load i18n %}

{% block body %}
<h3 class="text-center m-4"></h3>
{% if success %}
<div class="alert alert-success" role="alert">
  {% trans "New external permission added successfully!" %}
  <a href="{% url 'active_employees' %}" class="alert-link">{% trans "Employee list" %}</a>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card bg-light mb-3">
      <div class="card-header">
        <i class="fa-solid fa-key fa-lg"></i> {% trans "Add External Permission for" %} {{ employee.first_name }} {{ employee.last_name }}
      </div>
      <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data">  <!-- Add enctype attribute here -->
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">{% trans "Add" %}</button>
          <a href="{% url 'active_employees' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

employees/templates/employees/add_internal_permission.html
{% extends 'employees/base.html' %}
{% load i18n %}
{% block body %}
<h3 class="text-center m-4"></h3>
{% if success %}
<div class="alert alert-success" role="alert">
  {% trans "New internal permission added successfully!" %}
  <a href="{% url 'active_employees' %}" class="alert-link">{% trans "Employee list" %}</a>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card bg-light mb-3">
      <div class="card-header">
        <i class="fa-solid fa-key fa-lg"></i> {% trans "Add Internal Permission for" %} {{ employee.first_name }} {{ employee.last_name }}
      </div>
      <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data">  <!-- Add enctype attribute here -->
          {% csrf_token %}
          {{ form.as_p }}
          <button type="submit" class="btn btn-primary">{% trans "Add" %}</button>
          <a href="{% url 'active_employees' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

employees/templates/employees/base.html
{% load static %}

{% load i18n %}

<!DOCTYPE html>
<html lang="en">
<head>
    <meta charset="UTF-8">
    <title>SecureNest</title>
    <link rel="stylesheet" href="https://cdnjs.cloudflare.com/ajax/libs/font-awesome/6.5.1/css/all.min.css">
    <link href="{% static 'css/bootstrap.min.css' %}" rel="stylesheet">
    <link href="https://cdn.jsdelivr.net/npm/select2/dist/css/select2.min.css" rel="stylesheet" />
    <link href="https://cdn.jsdelivr.net/npm/select2-bootstrap4-theme/dist/select2-bootstrap4.min.css" rel="stylesheet">
</head>
<body class="d-flex flex-column min-vh-100">
<nav class="navbar navbar-expand-lg navbar-dark bg-primary">

    <div class="container-fluid">
        <a class="navbar-brand" href="{% url 'index' %}">
            <i class="fa-solid fa-fingerprint fa-lg"></i> SecureNest
        </a>
        <button class="navbar-toggler" type="button" data-bs-toggle="collapse" data-bs-target="#navbarColor01"
                aria-controls="navbarColor01" aria-expanded="false" aria-label="Toggle navigation">
            <span class="navbar-toggler-icon"></span>
        </button>

        <div class="collapse navbar-collapse" id="navbarColor01">
            <ul class="navbar-nav me-auto">
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'index' %}">
                        <i class="fa-solid fa-house fa-lg"></i> {% trans "Home" %}
                    </a>
                </li>
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'departments' %}">
                        <i class="fa-solid fa-building fa-lg"></i> {% trans "Departments" %}
                    </a>
                </li>
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" data-bs-toggle="dropdown" href="#" role="button" aria-haspopup="true"
                       aria-expanded="false">
                        <i class="fa-solid fa-users fa-lg"></i> {% trans "Employees" %}
                    </a>
                    <div class="dropdown-menu">
                        <a class="dropdown-item" href="{% url 'active_employees' %}"><i class="fa-solid fa-user-check fa-lg"></i> {% trans "Active" %}</a>
                        <a class="dropdown-item" href="{% url 'inactive_employees' %}"><i class="fa-solid fa-user-xmark fa-lg"></i> {% trans "Inactive" %}</a>
                        <div class="dropdown-divider"></div>
                        <a class="dropdown-item" href="{% url 'add' %}"><i class="fa-solid fa-user-plus fa-lg"></i> {% trans "Add Employee" %}</a>
                    </div>
                </li>
            </ul>


            <ul class="navbar-nav ms-auto">
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navLanguageDropdown" role="button"
                       data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-globe fa-lg"></i>
                    </a>
                    <ul class="dropdown-menu" aria-labelledby="navLanguageDropdown">
                        {% get_current_language as LANGUAGE_CODE %}
                        {% get_available_languages as LANGUAGES %}
                        {% for lang in LANGUAGES %}
                        <li>
                            <a class="dropdown-item" href="#"
                               onclick="event.preventDefault(); document.getElementById('form-{{ lang.0 }}').submit();">
                                {{ lang.1 }}
                            </a>
                            <form id="form-{{ lang.0 }}" action="{% url 'set_language' %}" method="post"
                                  style="display: none;">
                                {% csrf_token %}
                                <input type="hidden" name="language" value="{{ lang.0 }}">
                                <!-- Update this line to use get_full_path -->
                                <input type="hidden" name="next" value="{{ request.get_full_path }}">
                            </form>
                        </li>
                        {% endfor %}
                    </ul>
                </li>
                {% if request.user.is_authenticated %}
                <li class="nav-item dropdown">
                    <a class="nav-link dropdown-toggle" href="#" id="navbarDropdown" role="button" data-bs-toggle="dropdown" aria-expanded="false">
                        <i class="fa-solid fa-user fa-lg"></i> {% trans "Hello, " %}{{ request.user.username }}
                    </a>
                    <ul class="dropdown-menu dropdown-menu-end" aria-labelledby="navbarDropdown">
                        {% if request.user.is_superuser %}
                        <li><a class="dropdown-item" href="http://127.0.0.1:8000/admin"><i class="fa-solid fa-user-tie fa-lg"></i> {% trans "Admin" %}</a></li>
                        <li><hr class="dropdown-divider"></li>
                        {% endif %}
                        {% if request.user.is_superuser %}
                        <li><a class="dropdown-item" href="{% url 'create_invitation' %}"><i class="fa-solid fa-envelope-open-text fa-lg"></i> {% trans "Invite New User" %}</a></li>
                        <li><hr class="dropdown-divider"></li>
                        {% endif %}

                        <li><a class="dropdown-item" href="{% url 'user_settings' %}"><i class="fa-solid fa-gear fa-lg"></i> {% trans "Settings" %}</a></li>
                        <li><hr class="dropdown-divider"></li>
                        <li>
                            <form action="{% url 'logout' %}" method="post">
                                {% csrf_token %}
                                <button type="submit" class="dropdown-item"><i class="fa-solid fa-arrow-right-from-bracket fa-lg"></i> {% trans "Logout" %}</button>
                            </form>
                        </li>
                    </ul>
                </li>
                {% else %}
                <li class="nav-item">
                    <a class="nav-link" href="{% url 'login' %}">{% trans "Login" %}</a>
                </li>
                {% endif %}
            </ul>
        </div>
    </div>
</nav>
<div class="container-fluid">
    {% if messages %}
    <div class="mt-0"> <!-- 'mt-0' makes sure there's no top margin -->
    {% for message in messages %}
    <div class="alert {% if message.tags == 'error' %}alert-danger{% elif message.tags == 'success' %}alert-success{% else %}alert-{{ message.tags }}{% endif %} m-0" role="alert">
        {{ message }}
    </div>
    {% endfor %}
</div>
{% endif %}
    {% block body %}{% endblock %}
</div>
<footer class="footer mt-auto">
    <div class="text-center mb-3 mt-3">
        <span>Copyright &copy; <script>document.write(new Date().getFullYear())</script></span>
    </div>
</footer>
<script src="https://cdn.jsdelivr.net/npm/bootstrap@5.0.2/dist/js/bootstrap.bundle.min.js"></script>
</body>
</html>

employees/templates/employees/deactivate_employee.html
{% extends 'employees/base.html' %}
{% load i18n %}
{% block body %}
<h3 class="text-center m-4"></h3>
{% if success %}
<div class="alert alert-success" role="alert">
  {% trans "Employee deactivated successfully!" %}
  <a href="{% url 'inactive_employees' %}" class="alert-link">{% trans "Inactive Employee list" %}</a>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card bg-light mb-3">
      <div class="card-header">
        <i class="fa-solid fa-pen-to-square fa-lg"></i> {% trans "Deactivate Employee" %}: {{ employee.first_name }} {{ employee.last_name }}
      </div>
      <div class="card-body">
        <form action="" method="POST">
          {% csrf_token %}
          {{ form }}
          <button type="submit" class="btn btn-danger mt-3">{% trans "Deactivate" %}</button>
          <a href="{% url 'active_employees' %}" class="btn btn-secondary mt-3">{% trans "Cancel" %}</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}

employees/templates/employees/departments.html
{% extends 'employees/base.html' %}
{% load i18n %}

{% block body %}
<div class="row mt-4">
  <div class="col-12">
    {% if departments %}
    <div class="card bg-light ms-4 me-4 mb-4">
      <div class="card-header d-flex justify-content-between align-items-center">
        <div style="color: #e85d04;"><i class="fa-solid fa-building fa-lg" style="color: #e85d04;"></i>
          {% trans "Departments" %}</div>
      </div>
      <div class="card-body">
          <div class="mb-3"> <form method="get" action=".">
              <div class="input-group">
                {% if request.GET.q %}
                <a href="{% url 'departments' %}" class="btn btn-outline-secondary"><i class="fa fa-times"></i></a>
                {% endif %}
                <input type="text" class="form-control" placeholder="{% trans "Search for a department..." %}"
                       name="q" value="{{ request.GET.q }}"/>
                <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i>
                  {% trans "Search" %}</button>
              </div>
            </form>
          </div>
          <div class="table-responsive">
              <table class="table table-hover">
                <thead>
                  <tr>
                    <th scope="col"  class="small">{% trans "Department" %}</th>
                    <th scope="col" class="small">{% trans "Number of Employees" %}</th>
                  </tr>
                </thead>
                <tbody>
                {% for department, employee_count in departments %}
                <tr onclick="window.location.href='{% url 'active_employees' %}?department_id={{ department.id }}'">
                  <td>{{ department.name }}</td>
                  <td>{{ employee_count }}</td>
                </tr>
                {% empty %}
                {% endfor %}
                </tbody>
              </table>
          </div>
      </div>
    </div>
    {% else %}
    <div class="card bg-light ms-4 me-4 mb-4">
      <div class="card-header d-flex justify-content-between align-items-center">
        <div style="color: #e85d04;"><i class="fa-solid fa-building fa-lg" style="color: #e85d04;"></i>
          {% trans "Departments" %}</div>
      </div>
      <div class="card-body">
        <div class="mb-3"> <form method="get" action=".">
            <div class="input-group">
              {% if request.GET.q %}
                <a href="{% url 'departments' %}" class="btn btn-outline-secondary"><i class="fa fa-times"></i></a>
                {% endif %}
              <input type="text" class="form-control" placeholder="{% trans "Search for a department (starts with)..." %}"
                     name="q" value="{{ request.GET.q }}"/>
              <button class="btn btn-outline-secondary" type="submit"><i class="fa fa-search"></i>
                {% trans "Search" %}</button>
            </div>
          </form>
        </div>
        <div class="table-responsive">
          <table class="table table-hover">
            <thead>
              <tr>
                <th scope="col">{% trans "Department" %}</th>
                <th scope="col">{% trans "Number of Employees" %}</th>
              </tr>
            </thead>
          </table>
          <div class="text-center">
            <h6>{% trans "No departments found." %}</h6>
          </div>
        </div>
      </div>
    </div>
    {% endif %}
  </div>
</div>
{% endblock %}

employees/templates/employees/edit.html
{% extends 'employees/base.html' %}
{% load i18n %}
{% block body %}
<h3 class="text-center m-4"></h3>
{% if success %}
<div class="alert alert-success" role="alert">
  {% trans "Employee updated successfully!" %}
  <a href="{% url 'active_employees' %}" class="alert-link">{% trans "Employee list" %}</a>
</div>
{% else %}
<div class="row justify-content-center">
  <div class="col-6">
    <div class="card bg-light mb-3">
      <div class="card-header">
        <i class="fa-solid fa-pen-to-square fa-lg"></i> {% trans "Update Employee" %}: {{ employee.first_name }} {{ employee.last_name }}
      </div>
      <div class="card-body">
        <form method="POST" action="" enctype="multipart/form-data">
          {% csrf_token %}
          {{ form.as_p }}
          {{ info_form.as_p }}
          <button type="submit" class="btn btn-primary">{% trans "Update" %}</button>
          <a href="{% url 'active_employees' %}" class="btn btn-secondary">{% trans "Cancel" %}</a>
        </form>
      </div>
    </div>
  </div>
</div>
{% endif %}
{% endblock %}